---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
unzip("activity.zip")
data<-read.csv("activity.csv", sep = ",", header = TRUE)
names(data)
dim(data)
data$date <- as.Date(data$date)
summary(data)
```

## What is mean total number of steps taken per day?

```{r}
##Calculate and report the mean and median total number of steps taken per day
mean(data$steps, na.rm = TRUE)
median(data$steps, na.rm = TRUE)

##Make a histogram of the total number of steps taken each day
library(plyr)
s <- ddply(data,"date",summarize,steps=sum(steps))
library(ggplot2)
ggplot(s,aes(x=format(date,"%m-%d"),y=steps))+
        geom_bar(stat="identity")+
        labs(x="date")+
        theme(axis.text.x = element_text(angle = 90))+
        ggtitle("Number of steps per day in Oct-Nov")
```

## What is the average daily activity pattern?
```{r}
##Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
int<- ddply(data,"interval",summarize,steps=mean(steps,na.rm = TRUE))
plot(int, type="l", main="Average number of steps per interval in two months")

##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
max(int$steps, na.rm = TRUE)  ##206.1698
int[which.max(int$steps),]$interval   ##835

```

## Imputing missing values
```{r}
##Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
summary(data$steps)
sum(is.na(data))

##Devise a strategy for filling in all of the missing values in the dataset.
data2<-read.csv("activity.csv", sep = ",", header = TRUE)
data$date <- as.Date(data$date)
        ##Strategy: Impute NAs with the mean value of each interval

int_mean<- function (interval){
        int[int$interval==interval,]$steps}

##Create a new dataset that is equal to the original dataset but with the missing data filled in.
data_noNAs<-data2
for(i in 1:nrow(data_noNAs)){
    if(is.na(data_noNAs[i,]$steps)){
        data_noNAs[i,]$steps <- int_mean(data_noNAs[i,]$interval)
    }
}

##Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
sum_steps<- ddply(data_noNAs,"date",summarize,steps=sum(steps))
sum_steps$date <- as.Date(sum_steps$date)
ggplot(sum_steps,aes(x=format(date,"%m-%d"),y=steps))+
        geom_bar(stat="identity")+
        labs(x="date")+
        theme(axis.text.x = element_text(angle = 90))+
        ggtitle("Number of steps per day in Oct-Nov. Imputed dataset")

##Average of steps per day in data original and data imputed
data_NAs<- ddply(data,"date",summarize,steps=mean(steps))
data_noNAsaverage<- ddply(data_noNAs,"date",summarize,steps=mean(steps))
summary(data_NAs$steps)
summary(data_noNAsaverage$steps)

##Mean values do not change with values imputed. Median increased 0.01 % from the original value:
##(37.3826/37.37847)*100-100 = 0.01104914
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
##Create a new factor variable in the dataset with two levels -- "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
data_noNAs$date<- as.Date(strptime(data_noNAs$date, format="%Y-%m-%d"))
data_noNAs$day<-weekdays(data_noNAs$date)
for (i in 1:nrow(data_noNAs)) {
        if (data_noNAs[i,]$day %in% c("Saturday", "Sunday")){
            data_noNAs[i,]$day<-"weekend"    
        }
        else{
                data_noNAs[i,]$day<-"weekday"
        }
}
                
   ##average by weekday/weekend
data_noNAs2<-data_noNAs
meansteps_w<- ddply(data_noNAs2,.(interval, day),summarize,steps=mean(steps))

##Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).
ggplot(meansteps_w,aes(x=interval,y=steps))+
        geom_line(stat="identity", size=1, color="purple")+
        facet_wrap(~day, dir="v")+
        labs(x="interval", y="average steps")+
        ggtitle("Average steps taken in a weekday/weekend")

```



